### ISSUE TITLE
Kerning is too long when writing vertically

### ISSUE THREAD

**Issue by KaoruHOSOKAWA** [notofonts/hentaigana#9]
![Image](https://github.com/user-attachments/assets/d66b29df-ed29-464f-910a-51a383ef94f5)

It's too long when written vertically.

```css
body {
    font-family: "Noto Serif JP", "Noto Serif Hentaigana";
    writing-mode: vertical-rl;
}
```
